name: Build Linux Artifacts

on:
  push:
    branches: [ "qml" ]
  pull_request:
    branches: [ "qml" ]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ libssl-dev
          sudo apt-get install -y qt6-base-dev qt6-base-dev-tools qt6-declarative-dev qt6-svg-dev qt6-tools-dev qt6-tools-dev-tools
          
      - name: Build Project
        run: |
          cd src
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/$(uname -m)-linux-gnu/cmake/Qt6
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.arch }}-binaries
          path: src/build/*
